### ISSUE TITLE
Error 500 with script infinibox_volumes_workload_graphite.py 

### ISSUE THREAD

**Issue by jeedee5** [viawest/infinibox-graphite#1]
Hi,

When I run the script "infinibox_volumes_workload_graphite.py", I get an error 500. This script doesn't seem to log much data. 
I don't seem to have issues with the other scripts

I am running the script like below:
python infinibox_volumes_workload_graphite.py -u "http://infinimetrics.domain.name/api/rest/" -F "Infinidat.domain.name" -C "systems/0000/monitored_entities" -f "format=json&page=last&sort=-timestamp" -U "admin" -P "password"

Generated error:
_CRITICAL: Could not get data when querying the Infinibox which returned (500)_

When running in Verbose mode,  I get the following additional error:

_You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.

r1
CRITICAL: Could not get data when querying the Infinibox which returned (500)_

**Comment by jasonchamiak** [comment]
I don't see the servername parameter specified in your example. This would be the shortname of the Infinibox array. Also, the use of the "-F" parameter is not valid. It should look similar to the following.

python.exe infinibox_workload_graphite.py -u http://infinimetrics_fqdn/api/rest/ -s infinibox_shortname -C systems/0000/monitored_entities/1/data -f format=json^&page=last^&page_size=1^&sort=-timestamp -U username -P password

Let me know if this works for you.

**Comment by jeedee5** [comment]
Jason,
My issue was about "infinibox_volumes_workload_graphite.py", not " infinibox_workload_graphite.py"

**Comment by jasonchamiak** [comment]
I apologize for the mixup. Try the following.
- add “print url_args” after url_args.append() in the script and run the script again.
- log into your InfiniBox array using the same username and password used during script execution. Be sure to copy/paste the username and password from the command you’ve been running.
- Try to open each of the urls that were printed out from the script in the same browser.

Let me know if the pages load.

**Comment by jeedee5** [comment]
I didn't seem to get much additional output, when adding the print  command.
I also tried when using Verbose mode, together with some grep filtering, what didn't provide the expected output.

However, with the filtering, I suddenly saw following error. May this provide you with a clue?

Exception Type: DatabaseException at /api/rest/systems/1899/monitored_entities/32/data/
Exception Value: Code: 170, e.displayText() = DB::Exception: Bad get: has Int64, requested UInt64, e.what() = DB::Exception

I do seem to get a lot of output, but I think it just errors during execution

It looks to me that this request still works:
http://infinimetrics.domain.dns/api/rest/systems/1899/monitored_entities/30/data/?format=json&page=155929&page_size=1&sort=timestamp

while the next seems to fail (has page=last in the string instead of the ID)
http://infinimetrics.domain.dns/api/rest/systems/1899/monitored_entities/32/data/?format=json&page=last&page_size=1&sort=timestamp

**Comment by jeedee5** [comment]
volume ID 32, seems to be an ASYNC copy TARGET...

It doesn't seem to contain any performance data... I'll check a bit further to what is goining on here

**Comment by jeedee5** [comment]
with the sync/async targets, I seem to get 2 ID's for each target volume. The first one (ID 32), doesn't contain any perf data, the second one (ID 33) does.

Following is the API data of the monitored entities query

{
            "id": 32,
            "group": "Volumes",
            "type": "Volume",
            "name": "DC2-ID-ISCSI-ASync-target",
            "id_in_system": 2970,
            "gui_url": "http://infinibox1/#/volumes/2970",
            "polling_interval": 10,
            "created": "2018-02-02T12:04:01Z",
            "modified": "2018-02-14T10:06:02Z",
            "data": "http://infinimetrics.domain.dns/api/rest/systems/1899/monitored_entities/32/data/"
        },
        {
            "id": 33,
            "group": "Replication",
            "type": "monitored replica stats",
            "name": "DC2-ID-ISCSI-ASync-target",
            "id_in_system": 2977,
            "gui_url": "http://infinibox1/#/replication",
            "polling_interval": 10,
            "created": "2018-02-02T12:35:50Z",
            "modified": "2018-02-14T11:00:03Z",
            "data": "http://infinimetrics.domain.dns/api/rest/systems/1899/monitored_entities/33/data/"

**Comment by jeedee5** [comment]
following is the response of the query:  "GET /api/rest/systems/1899/monitored_entities/32/data/"

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "error": null,
    "result": [],
    "metadata": {
        "pages_total": 0,
        "page_size": 50,
        "next": null,
        "ready": true,
        "number_of_objects": 0,
        "page": 1,
        "previous": null
    }
}

**Comment by jasonchamiak** [comment]
One thing to note is that in some of 2.x versions of Infinimetrics, page=last does not work. This was fixed in v3.0.1.

https://support.infinidat.com/hc/en-us/articles/202603691-InfiniMetrics-Release-Notes-and-User-Guide

What version of Infinimetrics are you running? What OS/Version are you using to run the scripts from? What version software is running on your InfiniBox?

**Comment by jeedee5** [comment]
infinimetrics 4.1
Infinibox System 4.0.1.10

python and Grafana is running from from a Debian 8.7 (we already use Grafana for Netapp Monitoring. For this we use the NABOX virtual appliance)

**Comment by jasonchamiak** [comment]
I have a lab unit that was recently upgraded to 4.0. I'll test the code out against that device and will get back to you.

**Comment by jasonchamiak** [comment]
Have you added any volumes in Infinimetrics? Hosts are automatically populated in Infinimetrics but volumes are not unfortunately. That could be reason why the other scripts run and this one does not. I tested the script against my 4.0 InfiniBox and it is completing successfully.

**Comment by jasonchamiak** [comment]
Are you still having issues executing the script?

**Comment by jeedee5** [comment]
yes, I am still having issues...  I didn't have any time last week, so I'll continue to look into it this week.

**Comment by jeedee5** [comment]
hi,
I'm still in trouble... I deployed a new server to run the scripts on, but I still have the same problem. 
I added some more outputs to the script, and it fails during the processing of "#append infinimetrics api urls" 

This generates a list of volumes to process, but 1 of them generates an error on the output.
Following is a part of the url's:
url=http://infinimetrics.global.dns/api/rest/systems/1789/monitored_entities/49/data/?format=json&page=last&page_size=1&sort=timestamp
url=http://infinimetrics.global.dns/api/rest/systems/1789/monitored_entities/50/data/?format=json&page=last&page_size=1&sort=timestamp
url=http://infinimetrics.global.dns/api/rest/systems/1789/monitored_entities/53/data/?format=json&page=last&page_size=1&sort=timestamp

When checking the url's manually, all generate the expected performance output, except for volume "50"

volume 50 is an Async Target volume.

Folowing is the error when entering the URL
DatabaseException at /api/rest/systems/1789/monitored_entities/50/data/
Code: 170, e.displayText() = DB::Exception: Bad get: has Int64, requested UInt64, e.what() = DB::Exception

**Comment by jasonchamiak** [comment]
I have confirmed that I can pull async target volume data from Infinimetrics which is connected to an InfiniBox running 3.0.36.0. Unfortunately, I don't have another InfiniBox running the 4.x codebase to test out replicated volumes with the script. Your issues appears to be related to either Infinimetrics itself or the InfiniBox sending replicated volume data to Infinimetrics being that the API call to Infinimetrics does not produce expected results. Are there other async target volumes that you can successfully pull data from via the Infinimetrics API? If you remove volume 50 from Infinimetrics, does the script complete successfully?

**Comment by jeedee5** [comment]
I'll see if I can remove that volume from infinimetrics...
Can't we use the filter option on the script, to remove all volume names that end with "target" ?

**Comment by jeedee5** [comment]
On line 113, I changed the filter from 
url_args = ["http://{}/api/rest/volumes?fields=name,id&page_size=1000".format(
to: 
url_args = ["http://{}/api/rest/volumes?name=like:DC2&fields=name,id&page_size=1000".format(

This is just a rough change, as our volume names are starting with the datacenter name (DC1 or DC2). If we replicate a volume from DC1 to DC2, we will have a volume in DC1 like "DC2-volname-target". So if I would filter just on all DC2 volumes, I will not see the "DC1 target" one...

I would rather have filtered with something like "not like *target", but this doens't seem to be available according to the API
http://infinimetrics.global.dns/api/docs/filtering/

**Comment by jeedee5** [comment]
line 113 of script infinibox_volumes_workload_graphite.py

**Comment by jeedee5** [comment]
After contact with Infinidat, I have changed the query now to the following:
url_args = ["http://{}/api/rest/volumes?rmr_target=eq:false&fields=name,id&page_size=1000".format(

initial testing seems to work for now...
