### ISSUE TITLE
Infinimetrics 4.2 deprecates TLS 1.0 - python script ssl error

### ISSUE THREAD

**Issue by ganzenman** [viawest/infinibox-graphite#2]
Hi,
after upgrading Infinimetrics to version 4.2 (Q1 2019), TLS version 1.0 is deprecated.
In favour of this version 1.2 is supported.
This leaves an issue for python scripts.

The error you might get: CRITICAL: Could not get data when querying the Infinibox
 (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)')

To cope with this problem we opened "functions.py" and altered this section:
 while i < len(api_url):
        try:
                        # make request
            r.append(requests.get(
                "%s" % (api_url[i]),
                auth=(username, password),
                timeout=timeout,
                verify=False
            ))

The 1 line that was added was: verify=False
this makes the python command run again, but fails in Grafana:
  "message": "Unable to load TLS certificate"

I've noticed we have a different "infinibox_hosts_workload_graphite.py" file at this line:
url_args = ["http://{}/api/rest/hosts?fields=name,id&page_size=1000&security_method=MUTUAL_CHAP".format(
while in the original file this is: url_args = ["http://{}/api/rest/hosts?fields=name,id&page_size=1000".format(

could this explain the error or must other files or config also be changed?

**Comment by jasonchamiak** [comment]
Hello,

I've updated the functions.py script and have been running on Infinimetrics 4.2.x without issue for a while now. The original functions.py script that you were using didn't have the SSL verification bypass in place and is useful if you are not using a CA supplied SSL certificate but you have already worked around that issue. I have not had any issues with Grafana. What version of Grafana are you using where in the process do you get the Grafana error? 

Thanks,

Jason

**Comment by ganzenman** [comment]
Jason,
we're running grafana 5.4.0
When updating our py scripts they return results, like they did yesterday.
But the dashboards are giving this error:   "message": "Unable to load TLS certificate"
I've left our changes active, so i guess we should just use your updated version?

**Comment by ganzenman** [comment]
Running the updates scripts i get this output:
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

it's just a warning, but it seems grafana is struggling with it

**Comment by jasonchamiak** [comment]
Hello,

I made some minor changes to the scripts and tested in my lab using self-signed certs and the scripts execute without issue. Can you download the uploaded scripts and try again?

Thanks,

Jason

**Comment by ganzenman** [comment]
A reconfigure of the grafana datasource and using the changes you made on the 5th of Feb did the trick.
Great!
